//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public int ID { get; set; }
        public string kullanici_adi { get; set; }
        public string kullanici_email { get; set; }
        public string kullanici_sifre { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public System.DateTime dogum_tarihi { get; set; }
        public string cinsiyet { get; set; }
    }
}
